#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { createServer } from "vite";

const matrixPath = new URL("../docs/quality/public-claim-review-matrix-2026-07-12.md", import.meta.url);
const receiptPath = new URL("../docs/quality/public-claim-review-receipt-2026-07-12.md", import.meta.url);
const mode = process.argv.includes("--write") ? "write" : process.argv.includes("--check") ? "check" : "print";

const escapeCell = (value) => String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
const sha256 = (value) => createHash("sha256").update(value).digest("hex");

const server = await createServer({
  root: process.cwd(),
  server: { middlewareMode: true },
  appType: "custom",
  logLevel: "silent",
});

let data;
let ladder;
try {
  data = await server.ssrLoadModule("/src/data/publicStatements.ts");
  ladder = await server.ssrLoadModule("/src/lib/publicClaimLadder.ts");
} finally {
  await server.close();
}

ladder.validatePublicClaimContract();

const review = data.publicClaimReview;
const promptSha = sha256(data.publicClaimReviewPrompt);
const statementById = new Map(data.publicStatements.map((statement) => [statement.id, statement]));
const reviewedPayloadSha = sha256(JSON.stringify({
  statements: data.publicStatements,
  ladder: ladder.publicClaimLadder,
  reviewPrompt: data.publicClaimReviewPrompt,
  upstreamCommit: review.upstreamCommit,
  websiteBaselineCommit: review.websiteBaselineCommit,
  reviewer: review.reviewer,
  accountableOwner: review.accountableOwner,
  ownerAcceptanceStatus: review.ownerAcceptanceStatus,
  overallOutcome: review.overallOutcome,
  gateSatisfied: review.gateSatisfied,
  limitations: review.limitations,
  routeBundles: ladder.publicClaimRouteBundleSnapshot,
}));

if (reviewedPayloadSha !== review.reviewedPayloadSha256) {
  throw new Error(
    `Reviewed claim payload changed without a fresh reviewer receipt: expected ${review.reviewedPayloadSha256}, found ${reviewedPayloadSha}`,
  );
}

const matrixRows = ladder.publicClaimLadder.map((item) => {
  const statement = statementById.get(item.statementId);
  const sources = statement.sources
    .map((source) => `${source.path} (${source.passage}; commit ${source.commit}; SHA-256 ${source.sha256}; ${source.registryStatus.join(", ")})`)
    .join("<br>");
  return `| ${escapeCell(item.id)} | ${escapeCell(item.state)} | ${escapeCell(statement.id)} | ${escapeCell(statement.exactWording)} | ${escapeCell(statement.allowedQualification)} | ${escapeCell(sources)} | ${escapeCell(statement.forbiddenOverreads.join("; "))} | ${escapeCell(statement.disposition)} |`;
});

const matrix = `<!-- Generated by scripts/generate_public_claim_review.mjs. Do not edit by hand. -->
# FE-P0-05 Public Claim Review Matrix

Date: ${review.reviewDate}  
Upstream source commit: \`${review.upstreamCommit}\`  
Review ID: \`${review.reviewId}\`  
Disposition: \`${review.overallOutcome}\`

## Authority boundary

This matrix is website publication-governance evidence. The upstream registered
TeX sources and registries remain authoritative. The spawned AI reviewer is not
a human degree holder, external peer reviewer, signatory, proof authority, or
source of independent scientific validation. No public route consumes this
registry in FE-P0-05.

## Six-state claim-copy-source matrix

| Ladder ID | State | Statement ID | Exact candidate wording | Required qualification | Pinned source and passage | Forbidden overreads | Disposition |
| --- | --- | --- | --- | --- | --- | --- | --- |
${matrixRows.join("\n")}

## Prohibited statements

${data.unsafePublicClaimExamples.map((example) => `- \`${example}\``).join("\n")}

## Review limitations

${review.limitations.map((limitation) => `- ${limitation}`).join("\n")}

## References

The Æther Flow Project. (2026a). *Æther Flow exact-closure flagship article*
[TeX source]. \`ontology/tex/aether_flow_exact_closure_flagship_article.tex\`.

The Æther Flow Project. (2026b). *Æther Flow exact-closure sequence overview*
[TeX source]. \`ontology/tex/aether_flow_exact_closure_sequence_overview.tex\`.

The Æther Flow Project. (2026c). *TeX source registry* [CSV registry].
\`registries/TEX_SOURCE_REGISTRY.csv\`.

The Æther Flow Website. (2026). *Frontend recommendations implementation plan*.
\`ImplementationPlans/recomendation_frontend.md\`.
`;

const receiptRows = data.publicStatements
  .map((statement) => `| ${statement.id} | ${statement.claimState} | ${statement.disposition} | ${statement.sources.map((source) => source.path).join("<br>")} | ${statement.sources.map((source) => source.sha256).join("<br>")} |`)
  .join("\n");

const receipt = `<!-- Generated by scripts/generate_public_claim_review.mjs. Do not edit by hand. -->
# FE-P0-05 Independent AI Technical-Review Receipt

Review ID: \`${review.reviewId}\`  
Review type: \`${review.reviewType}\`  
Review date: ${review.reviewDate}  
Review prompt SHA-256: \`${promptSha}\`  
Reviewed payload SHA-256: \`${reviewedPayloadSha}\`  
Website baseline commit: \`${review.websiteBaselineCommit}\`  
Upstream commit: \`${review.upstreamCommit}\`

## Reviewer identity and separation

| Field | Recorded value |
| --- | --- |
| Implementing task | \`${review.implementationTaskName}\` |
| Reviewing task | \`${review.reviewer.taskName}\` |
| Reviewer ID | \`${review.reviewer.id}\` |
| System class | \`${review.reviewer.systemClass}\` |
| Declared credentials | \`${review.reviewer.declaredCredentials}\` |
| Human | \`${review.reviewer.human}\` |
| External reviewer | \`${review.reviewer.external}\` |
| Independence scope | \`${review.reviewer.independenceScope}\` |
| Attribution | \`${review.reviewer.signatureType}\` |
| Accountable human owner | ${review.accountableOwner} |
| Owner status | \`${review.ownerAcceptanceStatus}\` |

## Reviewed rows

| Statement ID | State | Disposition | Authoritative source path | Source SHA-256 |
| --- | --- | --- | --- | --- |
${receiptRows}

## Outcome

Overall outcome: \`${review.overallOutcome}\`  
Gate satisfied: \`${review.gateSatisfied}\`

The review accepts these exact, qualified rows for the source-bounded candidate
registry. It does not authorize Home or Physics publication. Any wording,
qualification, source path, hash, commit, registry status, surface, reviewer,
or disposition change invalidates this receipt and requires a fresh review.

## Explicit limitations

${review.limitations.map((limitation) => `- ${limitation}`).join("\n")}

## References

The Æther Flow Project. (2026a). *Æther Flow exact-closure flagship article*
[TeX source]. \`ontology/tex/aether_flow_exact_closure_flagship_article.tex\`.

The Æther Flow Project. (2026b). *Æther Flow exact-closure sequence overview*
[TeX source]. \`ontology/tex/aether_flow_exact_closure_sequence_overview.tex\`.

The Æther Flow Website. (2026). *Public claim review matrix* [Generated quality
record]. \`docs/quality/public-claim-review-matrix-2026-07-12.md\`.
`;

const outputs = [
  [matrixPath, matrix],
  [receiptPath, receipt],
];

if (mode === "write") {
  for (const [path, content] of outputs) await writeFile(path, content, "utf8");
  process.stdout.write("Generated public claim review matrix and receipt.\n");
} else if (mode === "check") {
  const stale = [];
  for (const [path, content] of outputs) {
    let existing = "";
    try {
      existing = await readFile(path, "utf8");
    } catch {
      stale.push(path.pathname);
      continue;
    }
    if (existing !== content) stale.push(path.pathname);
  }
  if (stale.length) {
    process.stderr.write(`Public claim review evidence is missing or stale: ${stale.join(", ")}\n`);
    process.exitCode = 1;
  } else {
    process.stdout.write("Public claim review evidence is current.\n");
  }
} else {
  process.stdout.write(matrix);
  process.stdout.write("\n");
  process.stdout.write(receipt);
}
