"""Portable AgentJob control runtime."""

PROTOCOL_VERSION = "1.0.0"
PACKAGE_VERSION = "0.4.0"

CAPABILITY_AGENTJOB_CONTROL = "sys4ai.agentjob-control.v1"
CAPABILITY_CONTROL_RECORDS = "sys4ai.control-records.v1"
CAPABILITY_GOAL_RELAY_STATE = "sys4ai.goal-relay-state.v4"
CAPABILITY_GOAL_RELAY_STATE_READER_V1 = "sys4ai.goal-relay-state-reader.v1"
CAPABILITY_GOAL_RELAY_STATE_READER_V2 = "sys4ai.goal-relay-state-reader.v2"
CAPABILITY_GOAL_RELAY_STATE_READER_V3 = "sys4ai.goal-relay-state-reader.v3"
CAPABILITY_CONTINUATION_ENVELOPE = "sys4ai.continuation-envelope.v3"
CAPABILITY_THREAD_PROVIDER = "sys4ai.thread-provider.v2"
CAPABILITY_CONTINUOUS_THREAD_PROVIDER = "sys4ai.thread-provider.continuous.v1"
CAPABILITY_REPOSITORY_TOPOLOGY_ENFORCEMENT = "sys4ai.repository-topology-enforcement.v1"
